### ISSUE TITLE
Is the typeRoots config supported?

### ISSUE THREAD

**Issue by karthikiyengar** [ikatyang/dts-jest#251]
I was trying to write types for an external module and test them at the same time.

`tsc` is able to find the types that I'm currently writing using `typeRoots` on `tsconfig.json`. Currently, it fails with `Could not find a declaration file for module 'my-package'. '/node_modules/my-package/index.js' implicitly has an 'any' type.`

Could you please suggest how I could achieve such a setup?

**Comment by ikatyang** [comment]
We use the TypeScript API to load config and check types so everything in `compilerOptions` should be supported, just set it up as usual and specify the path to `tsconfig.json` in [`compiler_options`](https://github.com/ikatyang/dts-jest#configs).

**Comment by karthikiyengar** [comment]
Thanks for the quick reply. Could you please take a look at my `jest.json` / `tsconfig.json`
```json
{
    "testEnvironment": "node",
    "moduleFileExtensions": ["ts", "js", "json"],
    "testRegex": "/tests/.+\\.ts$",
    "transform": {"/tests/.+\\.ts$": "dts-jest/transform"},
    "globals": {
      "_dts_jest_": {
        "enclosing_declaration": true,
        "compiler_options": "./tsconfig.json"
      }
    },
    "reporters": [
      "default",
      "dts-jest/reporter"
    ]
  }
```

```json
{
  "compilerOptions": {
    "strict": true,
    "strictFunctionTypes": false,
    "target": "es6",
    "module": "commonjs",
    "typeRoots": [ "./templates", "./node_modules/@types"]
  },
}
```

`tsc` is perfectly able to find the typings - am I missing something here?

(I can make jest work using a manual reference like so `/// <reference path="../templates/index.d.ts" />`, but this is not ideal)

**Comment by ikatyang** [comment]
Sorry for the inconvenience, just published 22.0.4 with the fix for it.

**Comment by karthikiyengar** [comment]
@ikatyang - Works perfectly, thanks a lot for the brilliant library 😄

**Comment by oleersoy** [comment]
[Just added a note about this to this article](https://medium.com/@ole.ersoy/using-vanilla-npm-javascript-modules-with-typescript-5052ca503178).

When I added `typeRoots` initially to support local type definitions, I did not know that I also needed to re-add the `node_modules/@types` directory so I was getting errors saying that Jest could not find type definitions.
