### ISSUE TITLE
grouping with "describe" broken in v23

### ISSUE THREAD

**Issue by piotrwitek** [ikatyang/dts-jest#330]
Hi @ikatyang,
I have found a breaking change in `dts-jest-remap` tool when upgraded to dts-jest v23.

In v22 I was using code like this:

```ts
describe('Name of the group', () => {
  // @dts-jest:pass:snap
  Math.max(2); //=> 2
});
```

This was working fine for with `dts-jest-remap` in v22, but now in v23 it cannot match the snapshot name because it's prepending a describe block name string to the snapshot name:

```ts
exports[`A Name of the group Math.max(2) (type) should match snapshot 1`] = `"number"`;
```

@ikatyang would you be willing to update `dts-jest-remap` to correctly match snapshots wrapped in describe blocks?

I have reproduced the issue in my fork: https://github.com/piotrwitek/dts-jest/commit/2e2ee97aa890fdf3b09b5d33a9f518fd527ed136

Just run `npm run remap-integration` to see the error.

Thanks!

**Comment by ikatyang** [comment]
The `@dts-jest:group` flag is designed to be the replacement of `describe` and `test`, but it does not seem to be the case in your usecase. Any reason why do you want to use the raw `describe` instead of `@dts-jest:group`?

**Comment by piotrwitek** [comment]
Yeah I know it, for me the problem is it doesn't offer function scope so I can enclose and not leak variable names etc.

**Comment by ikatyang** [comment]
If I remember correctly, you should be able to use BlockStatement to achieve this goal:

```js
// @dts-jest:group Name of the group
{
  // @dts-jest:pass:snap
  Math.max(2); //=> 2
}
```

**Comment by piotrwitek** [comment]
@ikatyang I really like this suggestion 👍 Thanks!

It might be a good idea to include such an example in the docs as this is often required when writing tests and BlockStatement is not something common, at least I see it very rarely.

**Comment by ikatyang** [comment]
> It might be a good idea to include such an example in the docs as this is often required when writing tests and BlockStatement is not something common, at least I see it very rarely.

PRs welcome :)

**Comment by piotrwitek** [comment]
Here you go :) #331
