### ISSUE TITLE
Support TS 3.9 @ts-expect-error comment?

### ISSUE THREAD

**Issue by karlhorky** [ikatyang/dts-jest#388]
Hi @ikatyang,

First of all, thanks for the awesome project, really useful!

I was wondering what your feelings are on supporting [the `// @ts-expect-error` comments from TypeScript 3.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments).

Right now, my test files have errors in them (in the editor), because the lines after `// @dts-jest:fail:snap` should actually have an error:

![Screen Shot 2020-06-25 at 18 05 28](https://user-images.githubusercontent.com/1935696/85756093-cd4ca980-b70e-11ea-80dd-6c3bb40ebfcc.png)

What I would like to be able to do would be to use `// @ts-expect-error` either in the place of:

```ts
// @ts-expect-error
mergeArrays([]);
```

...or in addition to the `dts-jest` annotations:

```ts
// @dts-jest:fail:snap
// @ts-expect-error
mergeArrays([]);
```

or...

```ts
// @ts-expect-error
// @dts-jest:fail:snap
mergeArrays([]);
```

or even...

```ts
// @ts-expect-error @dts-jest:fail:snap
mergeArrays([]);
```

...none of which currently work.

Not sure if this is a feasible ask actually, but it would be nice to clean up more errors in my project!

**Comment by karlhorky** [comment]
Wow, super fast @ikatyang, thanks! I'll upgrade now!

**Comment by karlhorky** [comment]
Ah, just trying this out, I guess this doesn't allow using snapshots. I guess that means I need to remove my snapshots when upgrading to this.

I suppose this is not super critical, but it would be nice to be able to configure that as well, in case it should test against the snapshot:

```ts
// @ts-expect-error @dts-jest:fail:snap
```

The rest of the line after `@ts-ignore` or `@ts-expect-error` can be used to describe why the error is being suppressed, which seems to fit this use case:

> It is recommended practice to have the remainder of the comment following @ts-ignore explain which error is being suppressed.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments

---

In case you're open to this, but it would be a feature for later, I can also open a new issue for this.

**Comment by ikatyang** [comment]
Ah, sorry. I did not explain what the new usage is. Basically, `@ts-expect-error` is treated as an alias of `@dts-jest:fail`, which means you could use `// @ts-expect-error:snap [description]` to replace `// @dts-jest:fail:snap [description]`, and snapshots are still supported for sure.

Let me know if you have any question.

**Comment by karlhorky** [comment]
Ohh, didn't catch the `[flags]` in the readme there, sorry! Should have seen that.
