### ISSUE TITLE
assert not-any

### ISSUE THREAD

**Issue by ducin** [ikatyang/dts-jest#393]
First of all, thank you for providing this tool! It was missing in the TS ecosystem.

**Q**: is there any approach for asserting that the type of expression is not `any`? Anything else would be fine. Or, more generally, is it possible to assert that the type of an expression is different than the one given?

**Comment by ikatyang** [comment]
> Or, more generally, is it possible to assert that the type of an expression is different than the one given?

Comparing two types is not easy, see https://github.com/ikatyang/dts-jest/issues/290#issuecomment-438897003 for more detail.

> Q: is there any approach for asserting that the type of expression is not any?

We can probably add a `:not-any` flag to assert it.
