### ISSUE TITLE
Upgrade yargs?

### ISSUE THREAD

**Issue by karlhorky** [ikatyang/dts-jest#395]
Hi @ikatyang ! 

As I mentioned in [my comment](https://github.com/ikatyang/dts-jest/pull/377#issuecomment-672805442), would it be possible to upgrade `yargs`?

This would make it easier to upgrade `mem` for [the security vulnerability](https://github.com/sindresorhus/mem/commit/da4e4398cb27b602de3bd55f746efa9b4a31702b) (memory leak).

**Comment by ikatyang** [comment]
`yargs@>=15` drops support for Node 6, which is still supported here. I'd like to use the less impactful way to fix this issue, does `yargs@14.x` fix that security vulnerability?

**Comment by karlhorky** [comment]
`yargs@14.2.0` no longer depends on `os-locale`, so this would fix the issue in a different way, yes!

**Comment by karlhorky** [comment]
Thanks! `23.3.0` fixes it :)
